spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      enable-statistics: true
      time-to-live: 2500ms
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
management:
  endpoints:
    web:
      base-path: ${ACTUATOR_URL}
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always